name: "Code check"

on:
  push:
    branches:
      - "main"

  workflow_call:

  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "composer.json"
      - "ecs.php"
      - "rector.php"
      - "phpstan.neon"

concurrency:
  group: conventions-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code:
    name: "Code check"
    strategy:
      matrix:
        phpVersion: [ "8.1", "8.2", "8.3" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-check.yml@b60da7b83d3d6e71ba2ec59d8ea1b98f48aae558
    secrets: inherit

  tests:
    name: "Run tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: bash tests/test.sh

